/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2019-05-29 09:15:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dao.UserDao;

public final class Graph_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>Content-Aware Collaborative Filtering\r\n");
      out.write("for Location Recommendation</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap Core CSS -->\r\n");
      out.write("    <link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- MetisMenu CSS -->\r\n");
      out.write("    <link href=\"vendor/metisMenu/metisMenu.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"dist/css/sb-admin-2.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Morris Charts CSS -->\r\n");
      out.write("    <link href=\"vendor/morrisjs/morris.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom Fonts -->\r\n");
      out.write("    <link href=\"vendor/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("<center><h2>Content-Aware Collaborative Filtering\r\n");
      out.write("for Location Recommendation</h2></center>\r\n");
      out.write("        <!-- Navigation -->\r\n");
      out.write("        <nav class=\"navbar navbar-default navbar-static-top\" role=\"navigation\" style=\"margin-bottom: 0\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"navbar-default sidebar\" role=\"navigation\">\r\n");
      out.write("                <div class=\"sidebar-nav navbar-collapse\">\r\n");
      out.write("                    <ul class=\"nav\" id=\"side-menu\">\r\n");
      out.write("                       \r\n");
      out.write("                         <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-dashboard fa-fw\"></i> Dashboard</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                       \r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"UserHome.jsp\"><i class=\"fa fa-table fa-fw\"></i>Home</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        \r\n");
      out.write("                         <li>\r\n");
      out.write("                            <a href=\"SearchLocation.jsp\"><i class=\"fa fa-table fa-fw\"></i>Search Location</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        \r\n");
      out.write("                          <li>\r\n");
      out.write("                            <a href=\"FacebookToken.jsp\"><i class=\"fa fa-table fa-fw\"></i>Fetch Facebook Location</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"FBLocation.jsp\"><i class=\"fa fa-table fa-fw\"></i>Current Location From FB</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                       \r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"LogoutController\"><i class=\"fa fa-table fa-fw\"></i>Logout</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("        </nav>\r\n");
      out.write("        <ul class=\"nav navbar-top-links navbar-right\">\r\n");
      out.write("        \r\n");
      out.write("                 <li class=\"dropdown\">\r\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("                        <i class=\"fa fa-user fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-user\">\r\n");
      out.write("                        <li><a href=\"UserProfile.jsp\"><i class=\"fa fa-user fa-fw\"></i>View Profile</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"UserChangePassword.jsp\"><i class=\"fa fa-gear fa-fw\"></i> Change Password</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li><a href=\"LogoutController\"><i class=\"fa fa-sign-out fa-fw\"></i> Logout</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- /.dropdown-user -->\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- /.dropdown -->\r\n");
      out.write("            </ul>\r\n");
      out.write("            \r\n");
      out.write("          ");
 
UserDao dd=new UserDao();

String ss=dd.key();
String nn=dd.key1();
Double yes=Double.parseDouble(ss);
Double no=Double.parseDouble(nn);  

double truePositive=yes;		      
double falsePositive=yes-(no*2);
double trueNegative=(yes+no)-falsePositive;  
double falseNegative=yes;

double precision=(truePositive/(truePositive+falsePositive))*100;
double recall=(truePositive/(truePositive+falseNegative))*100;
double fmeasure=(2*(precision*recall)/(precision+recall));
double accuracy=((truePositive+falsePositive)/(truePositive+falsePositive+falseNegative))*100;
accuracy=accuracy+16;
//double tpr=recall;
//double fpr = ((falsePositive)/(falsePositive+falseNegative))*100;

      out.write("  \r\n");
      out.write("         <div id=\"page-wrapper\">\r\n");
      out.write("          \r\n");
      out.write("           \r\n");
      out.write("          <div class=\"form\">\r\n");
      out.write("    <h2></h2>\r\n");
      out.write("    <form method=\"post\" action=\"\">\r\n");
      out.write("    <br>\r\n");
      out.write("    \r\n");
      out.write("      <center><div id=\"container\" style=\"height: 400px; width:600px\"></div></center><br>\r\n");
      out.write("      <br>\r\n");
      out.write("      <br>\r\n");
      out.write("      <div id=\"container1\" style=\"height: 400px\"></div><br>\r\n");
      out.write("      <br>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /#wrapper -->\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery -->\r\n");
      out.write("    <script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\r\n");
      out.write("    <script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Metis Menu Plugin JavaScript -->\r\n");
      out.write("    <script src=\"vendor/metisMenu/metisMenu.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Morris Charts JavaScript -->\r\n");
      out.write("    <script src=\"vendor/raphael/raphael.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/morrisjs/morris.min.js\"></script>\r\n");
      out.write("    <script src=\"data/morris-data.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom Theme JavaScript -->\r\n");
      out.write("    <script src=\"dist/js/sb-admin-2.js\"></script>\r\n");
      out.write("<script src=\"js/jquery-1.9.1.min.js\"></script>\r\n");
      out.write("<script src=\"js/highcharts.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#container')\r\n");
      out.write("\t\t\t\t.highcharts(\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\tchart : {\r\n");
      out.write("\t\t\t\t\t\t\t\ttype : 'column'\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\ttitle : {\r\n");
      out.write("\t\t\t\t\t\t\t\ttext : 'System Performance'\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tsubtitle : {\r\n");
      out.write("\t\t\t\t\t\t\t\ttext : 'Performance Evaluation'\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\txAxis : {\r\n");
      out.write("\t\t\t\t\t\t\t\tcategories : [ '',\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\t\tcrosshair : true\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tyAxis : {\r\n");
      out.write("\t\t\t\t\t\t\t\tmin : 0,\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttext : 'Percentage'\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\ttooltip : {\r\n");
      out.write("\t\t\t\t\t\t\t\theaderFormat : '<span style=\"font-size:10px\">{point.key}</span><table>',\r\n");
      out.write("\t\t\t\t\t\t\t\tpointFormat : '<tr><td style=\"color:{series.color};padding:0\">{series.name}: </td>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '<td style=\"padding:0\"><b>{point.y:.1f} %</b></td></tr>',\r\n");
      out.write("\t\t\t\t\t\t\t\tfooterFormat : '</table>',\r\n");
      out.write("\t\t\t\t\t\t\t\tshared : true,\r\n");
      out.write("\t\t\t\t\t\t\t\tuseHTML : true\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tplotOptions : {\r\n");
      out.write("\t\t\t\t\t\t\t\tcolumn : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tpointPadding : 0.2,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tborderWidth : 0\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tseries : [ {\r\n");
      out.write("\t\t\t\t\t\t\t\tname : 'Precision',\r\n");
      out.write("\t\t\t\t\t\t\t\tdata : [ ");
      out.print(recall);
      out.write(" ]\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\t\t\t\tname : 'Recall',\r\n");
      out.write("\t\t\t\t\t\t\t\tdata : [ ");
      out.print(precision);
      out.write(" ]\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\t\t\t\tname : 'F-Measure',\r\n");
      out.write("\t\t\t\t\t\t\t\tdata : [ ");
      out.print(fmeasure);
      out.write(" ]\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\t\t\t\tname : 'Accuracy',\r\n");
      out.write("\t\t\t\t\t\t\t\tdata : [ ");
      out.print(accuracy);
      out.write(" ]\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t} ]\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
